# Generated by Django 5.0.2 on 2024-03-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_students_per_group',
            field=models.IntegerField(default=0),
        ),
    ]
